Maintenance for the ci-tests.yml file (#539)
- Update ci action versions per ci warnings

- Update python 3.6 to be excluded from ubuntu-latest
  - python 3.6 is not an included cached tool on the latest Ubuntu
    https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

- Not including 3.11 because its cchardet fails to build
  cchardet.cpp(196): fatal error C1083:
  Cannot open include file: 'longintrepr.h': No such file or directory

- Add double-quotes around all the version numbers. From reading the
  documentation this seems to be the standard.